plugins {
    id 'com.android.application'
}

android {
    namespace 'sk.tichastopa.app'
    compileSdk 34

    defaultConfig {
        applicationId 'sk.tichastopa.app'
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName '0.2.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}
